### PR TITLE
Locking

### LINKED ISSUE #6: Locking during increment
We had a situation where we were trying to lock the increment operation to the model. 
It would be nice to auto_lock the incremented field while saving.

### PR DESCRIPTION
**Pull request by michaelachrisco**
Fixes #6 
Feel free to squash before merge or I will rebase into one commit (whichever you prefer).

### CODE REVIEW

**Comment by michaelachrisco** [comment]
A couple of notes:
1. I went ahead and rubocop'ed the gem. Hope you dont mind.
2. The lock test needs a physical DB to connect to. I added database_cleaner gem to the development stack for truncation during tests. 
3. May need to add more tests for complete code coverage, but the solution may be good enough for a minor version upgrade.

**Comment by felipediesel** [comment]
@michaelachrisco I'll merge it, but lock support arguments, so is better to pass on the value that is set in @options. 

Also is better to default to false, so the gem continues to work as it is already working.

**Comment by michaelachrisco** [comment]
Ill add in your suggestions if you wait a bit on the merge.

**Comment by felipediesel** [comment]
Great!

**Comment by felipediesel** [comment]
Sorry about the delay. I forgot about it. 

Merged!

**Pull request merged**
