### PR TITLE
Allow to use proc for initial value

### PR DESCRIPTION
**Pull request by javierav**

### CODE REVIEW

**Comment by javierav** [comment]
Before this can be merged, #34 should be resolver first.

**Comment by felipediesel** [comment]
I'm not sure about this change. It worries me that it gives a lot of freedom, so it would be easy to break it when updates are released

**Comment by javierav** [comment]
I understand your concern, but here's my use case.

We use the gem to generate the auto-incremented reference for our invoices. A reference has the following format: "XXX-YYY", where XXX is the ID of the related model on which the invoice is being invoiced and YYY is an auto-incremented number starting with 001.

For example, for a customer whose database ID is 35, we need to generate the series "035-001", "035-002", "035-003", etc. And for another customer whose ID is 980, generate the series "980-001", "980-002", "980-003", etc.

That's why we need the initial value of a billing series to be able to be specified as a code block at least (we can skip using a method via a symbol, although it's common in Rails) in order to set that XXX.

**Comment by felipediesel** [comment]
@javierav I just don't see how this is related to this gem. You could get the same result using scope and combining the result in the model. If it works like you expect it feels more like a side effect than something expected

**Comment by javierav** [comment]
If anyone needs to make use of this functionality, I keep it updated at https://github.com/javierav/auto_increment/tree/initial-proc

**Pull request closed without merging**
